### ISSUE TITLE
Missing "target" option

### ISSUE THREAD

**Issue by JerryX** [hbxks18/super_admin#1]
`
D:\File\work\IdeaWorkspace\super_admin>cnpm start

> super_admin@0.1.0 start D:\File\work\IdeaWorkspace\super_admin
> node scripts/start.js

[HPM] Missing "target" option. Example: {target: "http://www.example.org"}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! super_admin@0.1.0 start: `node scripts/start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the super_admin@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zhaol\AppData\Roaming\npm-cache\_logs\2020-10-16T01_43_57_004Z-debug.log

D:\File\work\IdeaWorkspace\super_admin>npm start

> super_admin@0.1.0 start D:\File\work\IdeaWorkspace\super_admin
> node scripts/start.js

[HPM] Missing "target" option. Example: {target: "http://www.example.org"}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! super_admin@0.1.0 start: `node scripts/start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the super_admin@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zhaol\AppData\Roaming\npm-cache\_logs\2020-10-16T01_45_07_613Z-debug.log

D:\File\work\IdeaWorkspace\super_admin>node -v
v12.18.0

D:\File\work\IdeaWorkspace\super_admin>npm -v
6.14.4
`

**Comment by hbxks18** [comment]
不好意思，上的少。。。proxy问题，已经兼容处理了下
